---
- name: HAProxy 설치
  ansible.builtin.dnf:
    name:
      - haproxy
      - firewalld
    state: present

- name: firewalld 활성화
  ansible.builtin.systemd:
    name: firewalld
    state: started
    enabled: true

- name: HAProxy 설정 배포
  ansible.builtin.template:
    src: haproxy.cfg.j2
    dest: /etc/haproxy/haproxy.cfg
    owner: root
    group: root
    mode: "0644"
  notify: restart haproxy

- name: 방화벽 열기(HAProxy listen port)
  ansible.posix.firewalld:
    port: "{{ haproxy_listen_port }}/tcp"
    permanent: true
    state: enabled
    immediate: true

- name: HAProxy 시작/활성화
  ansible.builtin.systemd:
    name: haproxy
    state: started
    enabled: true
