---
# Gateway Role: Nginx Reverse Proxy (No Redis)

- name: Install Nginx
  dnf:
    name: nginx
    state: present

- name: Enable IP Forwarding (persistent)
  copy:
    content: "net.ipv4.ip_forward = 1\n"
    dest: /etc/sysctl.d/99-ip-forward.conf
    mode: '0644'

- name: Apply IP Forwarding
  command: sysctl -w net.ipv4.ip_forward=1
  changed_when: false

- name: Deploy Nginx Gateway Config
  template:
    src: nginx_gateway.conf.j2
    dest: /etc/nginx/conf.d/gateway.conf
    mode: '0644'
  notify: Restart Nginx

- name: Start and Enable Nginx
  service:
    name: nginx
    state: started
    enabled: yes

- name: Open firewall ports
  firewalld:
    port: "{{ item }}"
    permanent: yes
    state: enabled
    immediate: yes
  loop:
    - 80/tcp
    - 8080/tcp
  ignore_errors: yes
